---
- name: Create nginx drop-in configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nginx.prefix.config }}/http.d"

- name: Template nginx configuration
  template:
    src: "{{ item }}"
    dest: "{{ render_path }}"
  loop_control:
    label: "{{ render_path }}"
  vars:
    template_dir: "{{ role_path }}/templates"
    render_path: "{{ nginx.prefix.config }}/{{ item|strip_prefix(template_dir + '/')|strip_suffix('.j2') }}"
  with_fileglob:
    - "{{ role_path }}/templates/*.j2"
    - "{{ role_path }}/templates/http.d/*.j2"
  notify: Restart nginx
